{% set name = "csvtk" %}
{% set version = "0.31.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/shenwei356/csvtk/archive/v{{ version }}.tar.gz
  sha256: ac28ae180d58b0214521a2ba5881ac3daf676ee2c39157366fad6cb56a64ba86

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - csvtk --help

about:
  home: https://github.com/shenwei356/csvtk
  license: MIT
  license_file:
    - LICENSE
    - csvtk/license-files/
  summary: A cross-platform, efficient and practical CSV/TSV toolkit in Golang

extra:
  recipe-maintainers:
    - apcamargo
